package com.shevelev.my_footprints_remastered.ui.activity_main.fragment_create_footprint_map.model

import com.shevelev.my_footprints_remastered.ui.shared.mvvm.model.ModelBase

interface CreateFootprintMapFragmentModel : ModelBase