package com.shevelev.my_footprints_remastered.ui.activity_main.fragments_data_flow.update

import com.shevelev.my_footprints_remastered.common_entities.Footprint
import com.shevelev.my_footprints_remastered.ui.shared.fragments_data_pass.flow.FragmentsDataFlowConsumer

interface UpdateFootprintDataFlowConsumer : FragmentsDataFlowConsumer<Footprint>